{"data_type": "generated", "data": [{"error": "Traceback (most recent call last):\n  File \"main.py\", line 188, in <module>\n    main()\n  File \"main.py\", line 86, in main\n    pdf_entities_1 = read_file(nlp, input_file_param)\n  File \"C:\\Users\\eric.stringfellow\\Desktop\\Projects\\discover-document-clustering\\text_preprocessing\\preprocessing_funcs.py\", line 58, in read_file\n    return pdf_entities\nUnboundLocalError: local variable 'pdf_entities' referenced before assignment\n", "title": "Error"}]}